konekt/btikonekt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('konekt.urls')),
]

konekt/konekt/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views


app_name = 'konekt'
urlpatterns = [
    path('', views.search_index, name='search_view'),
    path('download/', views.format_cv),
    path('cvs/', views.listing_cv),
    path('cv/<int:candidate_id>/', views.detail_candidate),
    path('search/', views.search_candidate),
    path('add_candidate/', views.add_candidate, name='add_candidate'),
    path('edit_candidate/<int:candidate_id>/', views.edit_candidate, name='edit_candidate'),
    path('delete_candidate/<int:candidate_id>/', views.delete_candidate, name='delete_candidate'),
    # path('add_fullcandidate/', views.add_fullcandidate, name='add_fullcandidate'),
    path('candidates/', views.CandidateListView.as_view(), name='candidate_list'),
    path('candidates/<int:pk>/', views.CandidateDetailView.as_view(), name='candidate_detail'),
    path('candidates/add/', views.CandidateCreateView.as_view(), name='candidate_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

konekt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.io' %}"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>{% block page_title %}{% endblock %}</title>

    <script>

      var xhr = new XMLHttpRequest();
      xhr.open('GET', "https://bti-konekt-bot.azurewebsites.net/api/messages/tokens", true);
      xhr.setRequestHeader('Authorization', 'BotConnector ' + 'IY_G1sii4hs.ChPYoKcCOBtlu9jtvi0FB4vzIH_1BnLkgh4-QCWM_LQ');
      xhr.send();
      xhr.onreadystatechange = processRequest;

      function processRequest(e) {
        if (xhr.readyState == 4  && xhr.status == 200) {
          var response = JSON.parse(xhr.responseText);
          document.getElementById("chat").src="https://bti-konekt-bot.azurewebsites.net/embed/bti-konekt?t="+response
        }
      }

    </script>
  </head>

  <body class="body">
    <div class="layout">
      <header class="header">
        <div class="header-wrapper">
          <a href="/">
            <div class="header-brand">
              <img class="header-logo" title="BTI-Advisory" src="{% static 'img/logo_bti_orange.png' %}" alt="logo BTI-Advisory">
            </div>
          </a>
          <nav class="header-nav">
            <ul class="list list-header">
              <li class="list-element list-element-header">
                <a href="/" class="link link--nav">Accueil</a>
              </li>
              <li class="list-element list-element-header">
                <a href="/add_candidate/" class="link link--nav">Ajouter un&middot;e candidat&middot;e</a>
              </li>
              <li class="list-element list-element-header">
                <a href="/candidates/" class="link link--nav">Candidat&middot;e&middot;s</a>
              </li>
            </ul>
          </nav>
        </div>
      </header>

      <main class="main">
        <section class="main-section">
          <h1 class="title-huge">{% block body_title %}{% endblock %}</h1>

          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}

          {% block content %}{% endblock %}
        </section>

        <!--<section class="main-section main-section--bot">
          <div>
            <iframe src='https://webchat.botframework.com/embed/bti-konekt-bot?s=IY_G1sii4hs.ChPYoKcCOBtlu9jtvi0FB4vzIH_1BnLkgh4-QCWM_LQ' class="chatbot"></iframe>
          </div>
        </section>-->
      </main>

      <footer>

      </footer>
    </div>
    <script src="{% static 'js/main.js' %}" async></script>
  </body>

</html>

konekt/templates/candidate.html
{% extends 'base.html' %}

{% block page_title %}BTI Konekt - {{ candidate.name }}{% endblock %}
{% block body_title %}Fiche de {{ candidate.name }}{% endblock %}

{% block content %}
<section class="main-section-element">
  {% if candidate %}
  <h2 class="title-middle">{{ candidate.job }}</h2>
  <div class="content-wrapper content-wrapper--cvdesktop">
    <div class="content-wrapper-element">
      <div class="content-wrapper--flex">
        <div class="">
          <p class="text"><span class="text--bold">Téléphone : </span>{{ candidate.phone }}</p>
          <p class="text"><span class="text--bold">Email : </span>{{ candidate.email }}</p>
          <p class="text"><span class="text--bold">Adresse : </span>{{ candidate.address }}</p>
        </div>
        <div>
          <p class="text"><span class="text--bold">Mobilité : </span>{{ candidate.mobility }}</p>
          <p class="text"><span class="text--bold">Disponibilité : </span>{{ candidate.availability }}</p>
          <p class="text"><span class="text--bold">Statut : </span>{{ candidate.status }}</p>
          <p class="text"><span class="text--bold">Tarif : </span>{{ candidate.price }}</p>
        </div>
      </div>
    </div>

    <ul class="list list--flex">
      <li class="list-element"><a class="link link-content" href="{% url 'konekt:edit_candidate' candidate_id=candidate.id %}">Modifier</a></li>
      <li class="list-element"><a class="link link-content" href="{% url 'konekt:delete_candidate' candidate_id=candidate.id %}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce candidat ?')">Supprimer</a></li>
      <li class="list-element"><a class="link link-content" href="{% url 'konekt:add_candidate' %}">Ajouter un nouveau CV</a></li>
    </ul>
  </div>
  {% endif %}
</section>
{% endblock %}

konekt/templates/candidate_create.html
{% extends 'base.html' %}

{% block page_title %}BTI Konekt - Ajouter un candidat{% endblock %}

{% block content %}
<section class="main-section-element">
  <form action="" method="post">

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.non_form_errors }}

    <div class="form-wrapper">
      {{ form.name }}
      {{ form.job }}
      {{ form.address }}
      <div class="form-wrapper-element">
        {{ form.phone }}
        {{ form.email }}
      </div>
      <div class="form-wrapper-element">
        {{ form.status }}
        {{ form.availability }}
      </div>
      <div class="form-wrapper-element">
        {{ form.mobility }}
        {{ form.price }}
      </div>
    </div>
    <button class="button" type="submit">Ajouter un candidat</button>
  </form>
</section>
{% endblock content %}

konekt/templates/candidate_detail.html
{% extends 'base.html' %}

{% block page_title %}BTI Konekt - {{ candidate.name }}{% endblock %}

{% block body_title %}Détails de {{ candidate.name }}{% endblock %}

{% block content %}
<section class="main-section-element">
  {% if candidate %}
  <h2 class="title-middle">{{ candidate.job }}</h2>
  <p class="text">Dernière modification le {{ candidate.modified_at | date:'d F Y \à H\hi'}}.</p>

  <div class="content-wrapper content-wrapper--cvdesktop">

    <ul class="list list--flex">
      <li class="list-element"><a class="link link-content link-content--highlight" href="/download/?source=db&format=bti&id={{ candidate.id }}">Format BTI</a></li>
      <li class="list-element"><a class="link link-content link-content--highlight" href="/download/?source=db&format=yellow&id={{ candidate.id }}">Format Yellow IT</a></li>
      {% if candidate.link_cv %}
        <li class="list-element"><a class="link link-content link-content--highlight" href="{{ candidate.link_cv }}">Format Original</a></li>
      {% endif %}
    </ul>

    <article class="content-wrapper-element">
      <div class="content-wrapper--flex">
        <div class="wrapper--flex">
          <p class="text"><span class="text--bold">Téléphone : </span>{{ candidate.phone }}</p>
          <p class="text"><span class="text--bold">Email : </span>{{ candidate.email }}</p>
          <p class="text"><span class="text--bold">Adresse : </span>{{ candidate.address }}</p>
        </div>
        <div class="wrapper--flex">
          <p class="text"><span class="text--bold">Mobilité : </span>{{ candidate.mobility }}</p>
          <p class="text"><span class="text--bold">Disponibilité : </span>{{ candidate.availability }}</p>
          <p class="text"><span class="text--bold">Statut : </span>{{ candidate.status }}</p>
          <p class="text"><span class="text--bold">Tarif : </span>{{ candidate.price }}</p>
          <p class="text"><span class="text--bold">Salaire : </span>{{ candidate.salary }}</p>
        </div>
      </div>

      <article>
        <h1 class="title-middle">Education / Formations</h1>
        {% if candidate.educations.all %}
          {% for education in candidate.educations.all %}
          <article>
            <p class="text"><span class="text--bold">Date : </span>{{ education.date }}</p>
            <p class="text"><span class="text--bold">Nom : </span>{{ education.name }}</p>
          </article>
          {% endfor %}
        {% else %}
          <p>Ce candidat n'a pas de diplôme</p>
        {% endif %}
      </article>

      <article>
        <h1 class="title-middle">Expériences</h1>
        {% if candidate.experiences.all %}
          {% for experience in candidate.experiences.all %}
          <article>
            <h1 class="title-small">{{ experience.job_title }}</h1>
            <h2 class="title-small">{{ experience.company_name }}</h2>
            <p class="text"><span class="text--bold">Lieu : </span>{{ experience.job_location }}</p>
            <p class="text"><span class="text--bold">Début : </span>{{ experience.duration }}</p>
            <p class="text"><span class="text--bold">Description : </span>{{ experience.description }}</p>
            <p class="text"><span class="text--bold">Outils : </span>{{ experience.tools }}</p>
          </article>
          {% endfor %}
        {% else %}
          <p>Ce candidat n'a pas d'expérience</p>
        {% endif %}
      </article>

      <article>
        <h1 class="title-middle">Compétences</h1>
        {% if candidate.skills.all %}
          {% for skill in candidate.skills.all %}
            <p class="text"><span class="text--bold"></span>{{ skill.name }}</p>
          {% endfor %}
        {% else %}
          <p>Ce candidat n'a pas encore de compétences enregistrées</p>
        {% endif %}
      </article>
    </article>

    <ul class="list list--flex">
      <li class="list-element"><a class="link link-content" href="{% url 'konekt:edit_candidate' candidate_id=candidate.id %}">Modifier</a></li>
      <li class="list-element"><a class="link link-content" href="{% url 'konekt:delete_candidate' candidate_id=candidate.id %}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce&middot;tte candidat&middot;e ?')">Supprimer</a></li>
      <li class="list-element"><a class="link link-content" href="{% url 'konekt:add_candidate' %}">Ajouter un nouveau CV</a></li>
      <li class="list-element"><a class="link link-content"  href="{% url 'konekt:candidate_list' %}">Tou&middot;te&middot;s les candidat&middot;e&middot;s</a></li>
    </ul>
  </div>
  {% endif %}
</section>
{% endblock %}

konekt/templates/candidate_experiences_update.html
{% extends 'base.html' %}

{% block page_title %}Modification des expériences pour {{ candidate.name }}{% endblock %}

{% block content %}
<section class="main-section-element">
  <h2 class="title-middle">Expériences de {{ candidate.name }}</h2>
  <div class="content-wrapper content-wrapper--cvdesktop">
    <div class="content-wrapper-element">
      <form action="" method="post" enctype="multipart/form-data">
        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        {% csrf_token %}

        {{ form.management_form }}
        {{ form.non_form_errors }}

        {% for experience_form in form.forms %}
        <article>
          <h2 class="title-small">
            {% if experience_form.instance.id %}
              Experience #{{ experience_form.instance.id }}</h2>
            {% else %}
              {% if form.forms|length > 1 %}
                Add another experience
              {% else %}
                Add an experience
              {% endif %}
            {% endif %}
          </h2>

          {% for hidden_field in experience_form.hidden_fields %}
            {{ hidden_field.errors }}
          {% endfor %}
          <div class="form-wrapper">
            {{ experience_form.job_title }}
            <div class="form-wrapper-element">
              {{ experience_form.job_location }}
              {{ experience_form.company_name }}
            </div>
            <div class="form-wrapper-element">
              {{ experience_form.start_date }}
              {{ experience_form.end_date }}
            </div>
            {{ experience_form.description }}
          </div>
          {% if experience_form.nested %}
            <div class="indent">

              {{ experience_form.nested.management_form }}
              {{ experience_form.nested.non_form_errors }}

              <table>
                {% for tool_form in experience_form.nested.forms %}

                  <tr>
                    <td>
                      <em>
                        {% if tool_form.instance.id %}
                          Tool #{{ tool_form.instance.id }}
                        {% else %}
                          Add a tool
                        {% endif %}
                      </em>
                    </td>
                    <td>
                      {% for hidden_field in tool_form.hidden_fields %}
                        {{ hidden_field.errors }}
                      {% endfor %}

                      <table>
                        {{ tool_form.as_table }}
                      </table>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
          {% endif %}
        </article>
        {% endfor %}

        <hr>

        <p>
          <input type="submit" value="Update experiences">
          &nbsp; &nbsp;
          <a href="{{ candidate.get_absolute_url  }}">Cancel</a>
        </p>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

konekt/templates/candidate_list.html
{% extends 'base.html' %}

{% block page_title %}Candidat&middot;e&middot;s{% endblock %}

{% block body_title %}Voici tout&middot;e&middot;s les candidat&middot;e&middot;s :{% endblock %}

{% block content %}

<section class="main-section-element">
  <ul class="list list--column">
  {% if candidate_list %}
    {% for candidate in candidate_list %}
      <li class="list-element">
        <a class="link link-content" href="{{ candidate.get_absolute_url }}">{{ candidate.name }} - {{ candidate.job }}</a>
      </li>
    {% endfor %}

  {% else %}

    <li class="list-element">Il n'y a pas de candidat&middot;e à afficher</li>

  {% endif %}

    <li class="list-element"><a class="link link-content" href="{% url 'konekt:add_candidate' %}">Ajouter un&middot;e candidat&middot;e</a></li>
  </ul>
</section>
{% endblock content %}

konekt/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<section class="main-section">
  <h1 class="title-huge">Ce candidat a été supprimé</h1>
</section>
{% endblock %}

konekt/templates/form.html
{% extends 'base.html' %}

{% block page_title %}BTI Konekt - Ajouter un candidat{% endblock %}
{% block body_title %}BTI Konekt - {{ title }}{% endblock %}

{% block content %}
<section class="main-section-element">
  {% if edit %}
  <form method="post" action="{% url action_form candidate_id=candidate_id %}">
  {% else %}
  <form method="post" action="{% url action_form %}">
  {% endif %}
    {% csrf_token %}
    <div class="form-wrapper">
      {{ form.name }}
      {{ form.job }}
      {{ form.address }}
      <div class="form-wrapper-element">
        {{ form.phone }}
        {{ form.email }}
      </div>
      <div class="form-wrapper-element">
        {{ form.status }}
        {{ form.availability }}
      </div>
      <div class="form-wrapper-element">
        {{ form.mobility }}
        {{ form.price }}
      </div>
    </div>
    <button class="button" type="submit">{{ button }}</button>
  </form>
</section>
{% endblock %}

konekt/templates/fullform.html
{% extends 'base.html' %}

{% block page_title %}BTI Konekt - Ajouter un&middot;e candidat&middot;e{% endblock %}

{% block body_title %}BTI Konekt - {{ title }}{% endblock %}

{% block content %}
<section class="main-section-element">
  {% if edit %}
  <form method="post" action="{% url action_form candidate_id=candidate_id %}">
  {% else %}
  <h2 class="title-middle">Importez un cv au format pdf/doc</h2>

  <form class="form" method="post" enctype="multipart/form-data" action="{% url action_form %}">
    <div class="form-wrapper-element">
      <div class="form-group form-group--file-input">
        <div>
        {% csrf_token %}
          {% for f in cv_form %}
            <label class="form-label form-label--show" for="{{ f.auto_id }}">{{ f.label }} {% if f.field.required %} * {% endif %}</label>
            {{ f }}
          {% endfor %}
        </div>
      </div>
    </div>
    <button class="button" type="submit">Envoyer</button>
  </form>

  <h2 class="title-middle">Ou remplissez le formulaire </h2>
  <form method="post" action="{% url action_form %}">
  {% endif %}
    {% csrf_token %}
    <article class="article-wrapper">
      <h2 class="title-small">Coordonnées</h2>
      {% for f in can_form %}
        {% if forloop.counter|divisibleby:2 %}
            <div class="form-group">
              <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}</label>
              {{ f }}
              {{ f.errors }}
            </div>
          </div>
        {% else %}
          {% if forloop.last %}
            <div class="form-wrapper-element">
              <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}</label>
              {{ f }}
              {{ f.errors }}
            </div>
          {% else %}
          <div class="form-wrapper-element">
            <div class="form-group">
              <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}</label>
              {{ f }}
              {{ f.errors }}
            </div>
          {% endif %}
        {% endif %}
      {% endfor %}
    </article>

    <article id="educations-form" class="article-wrapper">
      <h2 class="title-small">Formations / Education</h2>
      {% for f in edu_formset.management_form %}
        {{ f }}
      {% endfor %}
      {% for edu_form in edu_formset %}
      <div class="education-form article-wrapper-element">
        <div class="form-wrapper">
          {% for f in edu_form %}
            {% if "DELETE" in f.auto_id %}
              <div class="container">
                <label class="form-label" for="{{ f.auto_id }}">{{ f.label }}</label>
                {{ f }}
                {{ f.errors }}
                <span class="checkmark"></span>
              </div></div>
            {% elif forloop.counter|divisibleby:2 %}
                <div class="form-group">
                  <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}</label>
                  {{ f }}
                  {{ f.errors }}
                </div>
              </div>
            {% else %}
              {% if forloop.last %}
                <div class="form-wrapper-element">
                  <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}</label>
                  {{ f }}
                  {{ f.errors }}
                </div>
              {% else %}
              <div class="form-wrapper-element">
                <div class="form-group">
                  <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}</label>
                  {{ f }}
                  {{ f.errors }}
                </div>
              {% endif %}
            {% endif %}
          {% endfor %}
        </div>
        <!--<button class="button button-delete delete-education-form-btn">Delete</button>-->
      </div>
      {% endfor %}
      <button id="add-education-form-btn" class="button">Ajouter une formation/diplôme</button>
    </article>

    <article id="experiences-form" class="article-wrapper">
      <h2 class="title-small">Expériences</h2>
      {% for f in exp_formset.management_form %}
        {{ f }}
      {% endfor %}
      {% for exp_form in exp_formset %}
      <div class="experience-form article-wrapper-element">
        <div class="form-wrapper">
          {% for f in exp_form %}
            {% if "DELETE" in f.auto_id %}
              <div class="container">
                <label class="form-label" for="{{ f.auto_id }}">{{ f.label }}</label>
                {{ f }}
                {{ f.errors }}
                <span class="checkmark"></span>
              </div></div>
            {% elif forloop.counter == 5 or forloop.counter == 6 or forloop.last %}
                <div class="form-group">
                  <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}{% if f.field.required %} * {% endif %}</label>
                  {{ f }}
                  {{ f.errors }}
                </div>
            {% elif forloop.counter|divisibleby:2 %}
                <div class="form-group form-input-element--half ">
                  <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}{% if f.field.required %} * {% endif %}</label>
                  {{ f }}
                  {{ f.errors }}
               </div>
              </div>
            {% else %}
              <div class="form-wrapper-element">
                <div class="form-group">
                  <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}{% if f.field.required %} * {% endif %}</label>
                  {{ f }}
                  {{ f.errors }}
                </div>
            {% endif %}
          {% endfor %}
        </div>
        <!--<button class="button button-delete delete-experience-form-btn">Delete</button>-->
      </div>
      {% endfor %}
      <button id="add-experience-form-btn" class="button">Ajouter une expérience</button>
    </article>

    <article id="skills-form">
      <h2 class="title-small">Compétences</h2>
      {% for f in skills_formset.management_form %}
        {{ f }}
      {% endfor %}
      {% for skills_form in skills_formset %}
      <div class="skill-form article-wrapper-element">
        <div class="form-wrapper">
          {% for f in skills_form %}
            {% if "DELETE" in f.auto_id %}
              <div class="container">
                <label class="form-label" for="{{ f.auto_id }}">{{ f.label }}</label>
                {{ f }}
                {{ f.errors }}
                <span class="checkmark"></span>
              </div>
            {% else %}
              <div class="form-group">
                <label class="form-label form-label--hide" for="{{ f.auto_id }}">{{ f.label }}</label>
                {{ f }}
                {{ f.errors }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
        <!--<button class="button button-delete delete-skill-form-btn">Delete</button>-->
      </div>
      {% endfor %}
      <button id="add-skill-form-btn" class="button">Ajouter une compétence</button>
    </article>
    <input class="button" type="submit" value="{{ button }}" />
  </form>
</section>
{% endblock %}

konekt/templates/index.html
{% extends 'base.html' %}

{% block page_title %}BTI Konekt - Accueil {% endblock %}
{% block body_title %}BTI Konekt - {{ title }}{% endblock %}

{% block content %}
<section class="main-section-element">
  <h1 class="title-middle">Veuillez renseigner le(s) critère(s) suivant(s)</h1>
  <p class="text">La recherche se fera sur Elasticsearch / TurnoverIT</p>
  <form class="form">
    <div class="form-wrapper">
      <div class="form-group">
        <label class="form-label form-label--hide" for="{{ form.job.auto_id }}">{{ form.job.label }}</label>
        {{ form.job }}
      </div>
      <div class="form-wrapper-element">
        <div class="form-group">
          <label class="form-label form-label--hide" for="{{ form.availability.auto_id }}">{{ form.availability.label }}</label>
          {{ form.availability }}
        </div>
        <div class="form-group">
          <label class="form-label form-label--hide" for="{{ form.price.auto_id }}">{{ form.price.label }}</label>
          {{ form.price }}
        </div>
      </div>
      <div class="form-wrapper-element">
        <div class="form-group">
          <label class="form-label form-label--hide" for="{{ form.mobility.auto_id }}">{{ form.mobility.label }}</label>
          {{ form.mobility }}
        </div>
        <div class="form-group">
          <label class="form-label form-label--hide" for="{{ form.status.auto_id }}">{{ form.status.label }}</label>
          {{ form.status }}
        </div>
      </div>
      <div class="form-wrapper-element">
        <div class="form-group">
          <label class="form-label form-label--hide" for="{{ form.experience.auto_id }}">{{ form.experience.label }}</label>
          {{ form.experience }}
        </div>
        <div class="form-group">
          <label class="form-label form-label--hide" for="{{ form.skills.auto_id }}">{{ form.skills.label }}</label>
          {{ form.skills }}
        </div>
      </div>
      <div>
        <button class="button" type="submit">{{ button }}</button>
      </div>
    </div>
  </form>
</section>

<section class="main-section-element">
  {% if results %}
    <h1 class="title-huge">Résultat de la recherche :</h1>
    <ul class="list">
    {% for mytuple in results %}
      <li class="list-element list-element--margin">
        <p class="text text--margin-bottom">Poste : <strong class="text--bold">{{ mytuple.0 }}</strong></p>
        <p class="text text--margin-bottom">{{ mytuple.1 }}, {{ mytuple.2 }}, {{ mytuple.3 }}, {{ mytuple.4 }}</p>
        <p class="text text--margin-bottom">Compétences : <em class="text--addash">{{ mytuple.5 }}</em></p>
        <ul class="list list--flex">
          <li class="list-element"><a class="link link-content link-content--highlight" href="/download/?source=es&format=bti&id={{ mytuple.6 }}">Format BTI</a></li>
          <li class="list-element"><a class="link link-content link-content--highlight" href="/download/?source=es&format=yellow&id={{ mytuple.6 }}">Format Yellow</a></li>
          <li class="list-element"><a class="link link-content link-content--highlight" href="{{ mytuple.7 }}">CV Original</a></li>
        </ul>
      </li>
    {% endfor %}
    </ul>
  {% elif not search_term %}

  {% elif not results %}

    <p class="text">Pas de résultat</p>
  {% endif %}
</section>

{% endblock %}

konekt/templates/merci.html
{% extends 'base.html' %}

{% block page_title %}BTI Konekt - Merci{% endblock %}

{% block content %}
    <h1 class="">Merci !</h1>
    <p>Le candidat <em>{{ candidate.name }}</em> vient d'être ajouté à la base.</p>

{% endblock %}

konekt/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>